#pragma once

#define HEAP_IDT_TAG                    ':TDI'
#define HEAP_PAGE_TAG                   'EGAP'
#define HEAP_CPU_TAG                    ':UPC'
#define HEAP_IPC_TAG                    ':CPI'
#define HEAP_GDT_TAG                    ':TDG'
#define HEAP_TEST_TAG                   ':TST'
#define HEAP_STACK_TAG                  ':KTS'
#define HEAP_PCI_TAG                    ':ICP'
#define HEAP_DISK_TAG                   ':KSD'
#define HEAP_VOLUME_TAG                 ':LOV'
#define HEAP_DEVICE_TAG                 ':VED'
#define HEAP_DEVICE_EXT_TAG             ':TXE'
#define HEAP_DRIVER_TAG                 ':VRD'
#define HEAP_IRP_TAG                    ':PRI'
#define HEAP_VPB_TAG                    ':BPV'
#define HEAP_TEMP_TAG                   ':PMT'
#define HEAP_FS_TAG                     ':SF '
#define HEAP_FILE_OBJECT_TAG            ':LIF'
#define HEAP_ACPICA_TAG                 'ACCA'
#define HEAP_ACPIIF_TAG                 'FICA'
#define HEAP_APIC_TAG                   'CIPA'
#define HEAP_THREAD_TAG                 ':RHT'
#define HEAP_MDL_TAG                    ':LMD'
#define HEAP_ATA_TAG                    ':ATA'
#define HEAP_IOMU_TAG                   ':MOI'
#define HEAP_MMU_TAG                    ':UMM'
#define HEAP_CORE_TAG                   ':ROC'
#define HEAP_NET_TAG                    ':TEN'
#define HEAP_ETH_TAG                    ':HTE'
#define HEAP_PORT_TAG                   ':TRP'
#define HEAP_EXECUTIVE_TAG              ':XE '
#define HEAP_PROCESS_TAG                ':CRP'
#define HEAP_BOOT_TAG                   'TOOB'