#pragma once

#include "cmd_common.h"

FUNC_GenericCommand CmdPrintVolumeInformation;
FUNC_GenericCommand CmdInfiniteRecursion;
FUNC_GenericCommand CmdRtcFail;
FUNC_GenericCommand CmdRangeFail;
FUNC_GenericCommand CmdBiteCookie;
FUNC_GenericCommand CmdLogSetState;
FUNC_GenericCommand CmdSetLogLevel;
FUNC_GenericCommand CmdSetLogComponents;
FUNC_GenericCommand CmdClearScreen;
FUNC_GenericCommand CmdRunAllFunctionalTests;
FUNC_GenericCommand CmdRunAllPerformanceTests;
