#include "HAL9000.h"
#include "idt.h"
#include "idt_handlers.h"
#include "gdt.h"
#include "cpu.h"

// exceptions
extern void DivideError();
extern void DebugException();
extern void NMIInterrupt();
extern void BreakpointException();
extern void OverflowException();
extern void BoundRangeExceededException();
extern void InvalidOpcode();
extern void DeviceNotAvailable();
extern void DoubleFault();
extern void CoprocessorSegmentOverrun();
extern void InvalidTSS();
extern void SegmentNotPresent();
extern void StackFault();
extern void GeneralProtection();
extern void PageFault();
extern void FloatingPointX87Error();
extern void AlignmentCheck();
extern void MachineCheck();
extern void FloatingPointSIMD();
extern void VirtualizationException();

#define GENERATE_GENERIC_NAME(x)    GenericIsr##x
#define IMPORT_GENERIC_ISR(x)       extern void GENERATE_GENERIC_NAME(x)();

IMPORT_GENERIC_ISR(32); IMPORT_GENERIC_ISR(33); IMPORT_GENERIC_ISR(34); IMPORT_GENERIC_ISR(35);
IMPORT_GENERIC_ISR(36); IMPORT_GENERIC_ISR(37); IMPORT_GENERIC_ISR(38); IMPORT_GENERIC_ISR(39);
IMPORT_GENERIC_ISR(40); IMPORT_GENERIC_ISR(41); IMPORT_GENERIC_ISR(42); IMPORT_GENERIC_ISR(43);
IMPORT_GENERIC_ISR(44); IMPORT_GENERIC_ISR(45); IMPORT_GENERIC_ISR(46); IMPORT_GENERIC_ISR(47);

IMPORT_GENERIC_ISR(48); IMPORT_GENERIC_ISR(49); IMPORT_GENERIC_ISR(50); IMPORT_GENERIC_ISR(51);
IMPORT_GENERIC_ISR(52); IMPORT_GENERIC_ISR(53); IMPORT_GENERIC_ISR(54); IMPORT_GENERIC_ISR(55);
IMPORT_GENERIC_ISR(56); IMPORT_GENERIC_ISR(57); IMPORT_GENERIC_ISR(58); IMPORT_GENERIC_ISR(59);
IMPORT_GENERIC_ISR(60); IMPORT_GENERIC_ISR(61); IMPORT_GENERIC_ISR(62); IMPORT_GENERIC_ISR(63);

IMPORT_GENERIC_ISR(64); IMPORT_GENERIC_ISR(65); IMPORT_GENERIC_ISR(66); IMPORT_GENERIC_ISR(67);
IMPORT_GENERIC_ISR(68); IMPORT_GENERIC_ISR(69); IMPORT_GENERIC_ISR(70); IMPORT_GENERIC_ISR(71);
IMPORT_GENERIC_ISR(72); IMPORT_GENERIC_ISR(73); IMPORT_GENERIC_ISR(74); IMPORT_GENERIC_ISR(75);
IMPORT_GENERIC_ISR(76); IMPORT_GENERIC_ISR(77); IMPORT_GENERIC_ISR(78); IMPORT_GENERIC_ISR(79);

IMPORT_GENERIC_ISR(80); IMPORT_GENERIC_ISR(81); IMPORT_GENERIC_ISR(82); IMPORT_GENERIC_ISR(83);
IMPORT_GENERIC_ISR(84); IMPORT_GENERIC_ISR(85); IMPORT_GENERIC_ISR(86); IMPORT_GENERIC_ISR(87);
IMPORT_GENERIC_ISR(88); IMPORT_GENERIC_ISR(89); IMPORT_GENERIC_ISR(90); IMPORT_GENERIC_ISR(91);
IMPORT_GENERIC_ISR(92); IMPORT_GENERIC_ISR(93); IMPORT_GENERIC_ISR(94); IMPORT_GENERIC_ISR(95);

IMPORT_GENERIC_ISR(96); IMPORT_GENERIC_ISR(97); IMPORT_GENERIC_ISR(98); IMPORT_GENERIC_ISR(99);
IMPORT_GENERIC_ISR(100); IMPORT_GENERIC_ISR(101); IMPORT_GENERIC_ISR(102); IMPORT_GENERIC_ISR(103);
IMPORT_GENERIC_ISR(104); IMPORT_GENERIC_ISR(105); IMPORT_GENERIC_ISR(106); IMPORT_GENERIC_ISR(107);
IMPORT_GENERIC_ISR(108); IMPORT_GENERIC_ISR(109); IMPORT_GENERIC_ISR(110); IMPORT_GENERIC_ISR(111);

IMPORT_GENERIC_ISR(112); IMPORT_GENERIC_ISR(113); IMPORT_GENERIC_ISR(114); IMPORT_GENERIC_ISR(115);
IMPORT_GENERIC_ISR(116); IMPORT_GENERIC_ISR(117); IMPORT_GENERIC_ISR(118); IMPORT_GENERIC_ISR(119);
IMPORT_GENERIC_ISR(120); IMPORT_GENERIC_ISR(121); IMPORT_GENERIC_ISR(122); IMPORT_GENERIC_ISR(123);
IMPORT_GENERIC_ISR(124); IMPORT_GENERIC_ISR(125); IMPORT_GENERIC_ISR(126); IMPORT_GENERIC_ISR(127);

IMPORT_GENERIC_ISR(128); IMPORT_GENERIC_ISR(129); IMPORT_GENERIC_ISR(130); IMPORT_GENERIC_ISR(131);
IMPORT_GENERIC_ISR(132); IMPORT_GENERIC_ISR(133); IMPORT_GENERIC_ISR(134); IMPORT_GENERIC_ISR(135);
IMPORT_GENERIC_ISR(136); IMPORT_GENERIC_ISR(137); IMPORT_GENERIC_ISR(138); IMPORT_GENERIC_ISR(139);
IMPORT_GENERIC_ISR(140); IMPORT_GENERIC_ISR(141); IMPORT_GENERIC_ISR(142); IMPORT_GENERIC_ISR(143);

IMPORT_GENERIC_ISR(144); IMPORT_GENERIC_ISR(145); IMPORT_GENERIC_ISR(146); IMPORT_GENERIC_ISR(147);
IMPORT_GENERIC_ISR(148); IMPORT_GENERIC_ISR(149); IMPORT_GENERIC_ISR(150); IMPORT_GENERIC_ISR(151);
IMPORT_GENERIC_ISR(152); IMPORT_GENERIC_ISR(153); IMPORT_GENERIC_ISR(154); IMPORT_GENERIC_ISR(155);
IMPORT_GENERIC_ISR(156); IMPORT_GENERIC_ISR(157); IMPORT_GENERIC_ISR(158); IMPORT_GENERIC_ISR(159);

IMPORT_GENERIC_ISR(160); IMPORT_GENERIC_ISR(161); IMPORT_GENERIC_ISR(162); IMPORT_GENERIC_ISR(163);
IMPORT_GENERIC_ISR(164); IMPORT_GENERIC_ISR(165); IMPORT_GENERIC_ISR(166); IMPORT_GENERIC_ISR(167);
IMPORT_GENERIC_ISR(168); IMPORT_GENERIC_ISR(169); IMPORT_GENERIC_ISR(170); IMPORT_GENERIC_ISR(171);
IMPORT_GENERIC_ISR(172); IMPORT_GENERIC_ISR(173); IMPORT_GENERIC_ISR(174); IMPORT_GENERIC_ISR(175);

IMPORT_GENERIC_ISR(176); IMPORT_GENERIC_ISR(177); IMPORT_GENERIC_ISR(178); IMPORT_GENERIC_ISR(179);
IMPORT_GENERIC_ISR(180); IMPORT_GENERIC_ISR(181); IMPORT_GENERIC_ISR(182); IMPORT_GENERIC_ISR(183);
IMPORT_GENERIC_ISR(184); IMPORT_GENERIC_ISR(185); IMPORT_GENERIC_ISR(186); IMPORT_GENERIC_ISR(187);
IMPORT_GENERIC_ISR(188); IMPORT_GENERIC_ISR(189); IMPORT_GENERIC_ISR(190); IMPORT_GENERIC_ISR(191);

IMPORT_GENERIC_ISR(192); IMPORT_GENERIC_ISR(193); IMPORT_GENERIC_ISR(194); IMPORT_GENERIC_ISR(195);
IMPORT_GENERIC_ISR(196); IMPORT_GENERIC_ISR(197); IMPORT_GENERIC_ISR(198); IMPORT_GENERIC_ISR(199);
IMPORT_GENERIC_ISR(200); IMPORT_GENERIC_ISR(201); IMPORT_GENERIC_ISR(202); IMPORT_GENERIC_ISR(203);
IMPORT_GENERIC_ISR(204); IMPORT_GENERIC_ISR(205); IMPORT_GENERIC_ISR(206); IMPORT_GENERIC_ISR(207);

IMPORT_GENERIC_ISR(208); IMPORT_GENERIC_ISR(209); IMPORT_GENERIC_ISR(210); IMPORT_GENERIC_ISR(211);
IMPORT_GENERIC_ISR(212); IMPORT_GENERIC_ISR(213); IMPORT_GENERIC_ISR(214); IMPORT_GENERIC_ISR(215);
IMPORT_GENERIC_ISR(216); IMPORT_GENERIC_ISR(217); IMPORT_GENERIC_ISR(218); IMPORT_GENERIC_ISR(219);
IMPORT_GENERIC_ISR(220); IMPORT_GENERIC_ISR(221); IMPORT_GENERIC_ISR(222); IMPORT_GENERIC_ISR(223);

IMPORT_GENERIC_ISR(224); IMPORT_GENERIC_ISR(225); IMPORT_GENERIC_ISR(226); IMPORT_GENERIC_ISR(227);
IMPORT_GENERIC_ISR(228); IMPORT_GENERIC_ISR(229); IMPORT_GENERIC_ISR(230); IMPORT_GENERIC_ISR(231);
IMPORT_GENERIC_ISR(232); IMPORT_GENERIC_ISR(233); IMPORT_GENERIC_ISR(234); IMPORT_GENERIC_ISR(235);
IMPORT_GENERIC_ISR(236); IMPORT_GENERIC_ISR(237); IMPORT_GENERIC_ISR(238); IMPORT_GENERIC_ISR(239);

IMPORT_GENERIC_ISR(240); IMPORT_GENERIC_ISR(241); IMPORT_GENERIC_ISR(242); IMPORT_GENERIC_ISR(243);
IMPORT_GENERIC_ISR(244); IMPORT_GENERIC_ISR(245); IMPORT_GENERIC_ISR(246); IMPORT_GENERIC_ISR(247);
IMPORT_GENERIC_ISR(248); IMPORT_GENERIC_ISR(249); IMPORT_GENERIC_ISR(250); IMPORT_GENERIC_ISR(251);
IMPORT_GENERIC_ISR(252); IMPORT_GENERIC_ISR(253); IMPORT_GENERIC_ISR(254); IMPORT_GENERIC_ISR(255);


#define CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(x)     \
        status = CREATE_INTERRUPT_GATE_DESC(GENERATE_GENERIC_NAME(x), (x), CodeSelector, 0); \
        ASSERT(SUCCEEDED(status));

#define CREATE_DUMMY_DESC(idx,cs,ist)                      IdtInstallDescriptor((idx),(cs),SystemSegment64BitInterruptGate,(ist),FALSE,NULL)

#define CREATE_TASK_GATE_DESC(addr,idx,cs,ist)             IdtInstallDescriptor((idx),(cs),SystemSegment64BitTaskGate,(ist),TRUE,(addr))

// The ONLY difference between an interrupt and a trap gate is that the
// INTERRUPT gate clears the IF flag => no more interrupts in the current handler
#define CREATE_INTERRUPT_GATE_DESC(addr,idx,cs,ist)        IdtInstallDescriptor((idx),(cs),SystemSegment64BitInterruptGate,(ist),TRUE,(addr))
#define CREATE_TRAP_GATE_DESC(addr,idx,cs,ist)             IdtInstallDescriptor((idx),(cs),SystemSegment64BitTrapGate,(ist),TRUE,(addr))

// The lower the value of the IST index the likelier it is for the exception to use the IST
// i.e. we may have a limited number of ISTs (define by the TSS to only 7)
// As a result we'll have some handlers using the same IST
#define IST_DB          5
#define IST_BP          6
#define IST_NMI         7
#define IST_DF          1
#define IST_NP          3
#define IST_SS          4
#define IST_GP          2
#define IST_MC          1

#define IST_CHOOSE(Cur,Max)     ((Cur)<=(Max) ? (Cur) : 0)

static
STATUS
_InitInternalHandlers(
    IN      WORD                CodeSelector,
    IN      BYTE                NumberOfTssStacks
    );

static
STATUS
_InitExternalInterruptHandlers(
    IN      WORD                CodeSelector
    );

STATUS
InitIdtHandlers(
    IN      WORD                CodeSelector,
    IN      BYTE                NumberOfTssStacks
    )
{
    STATUS status;

    LOG_FUNC_START;

    LOG_TRACE_INTERRUPT("Will Initialize handlers for CS 0x%x and %u TSS stacks\n",
                        CodeSelector, NumberOfTssStacks );

    status = _InitInternalHandlers(CodeSelector, NumberOfTssStacks);
    if (!SUCCEEDED(status))
    {
        LOG_FUNC_ERROR("_InitExceptionHandlers", status);
        return status;
    }

    status = _InitExternalInterruptHandlers(CodeSelector);
    if (!SUCCEEDED(status))
    {
        LOG_FUNC_ERROR("_InitInterruptHandlers", status);
        return status;
    }

    // lidt Idt
    IdtReload();

    LOG_FUNC_END;

    return status;
}

static
STATUS
_InitInternalHandlers(
    IN      WORD                CodeSelector,
    IN      BYTE                NumberOfTssStacks
    )
{
    STATUS status;

    status = STATUS_SUCCESS;

#pragma warning(push)
    // warning C4152: nonstandard extension, function/data pointer conversion in expression
#pragma warning(disable:4152)
    // 00 - #DE - Divide Error
    status = CREATE_INTERRUPT_GATE_DESC(DivideError, ExceptionDivideError, CodeSelector, 0);
    ASSERT(SUCCEEDED(status));

    // 01 - #DB - Debug Exception
    status = CREATE_INTERRUPT_GATE_DESC(DebugException, ExceptionDebugException, CodeSelector, IST_CHOOSE(IST_DB, NumberOfTssStacks));
    ASSERT(SUCCEEDED(status));

    // 02 - NMI - NMI Interrupt
    status = CREATE_INTERRUPT_GATE_DESC(NMIInterrupt, ExceptionNMI, CodeSelector, IST_CHOOSE(IST_NMI, NumberOfTssStacks));
    ASSERT(SUCCEEDED(status));

    // 03 - #BP - Breakpoint Exception
    status = CREATE_INTERRUPT_GATE_DESC(BreakpointException, ExceptionBreakpoint, CodeSelector, IST_CHOOSE(IST_BP, NumberOfTssStacks));
    ASSERT(SUCCEEDED(status));

    // 04 - #OF - Overflow Exception
    status = CREATE_INTERRUPT_GATE_DESC(OverflowException, ExceptionOverflow, CodeSelector, 0);
    ASSERT(SUCCEEDED(status));

    // 05 - #BR - BOUND Range Exceeded Exception
    status = CREATE_INTERRUPT_GATE_DESC(BoundRangeExceededException, ExceptionBoundRange, CodeSelector, 0);
    ASSERT(SUCCEEDED(status));

    // 06 - #UD - Invalid Opcode
    status = CREATE_INTERRUPT_GATE_DESC(InvalidOpcode, ExceptionInvalidOpcode, CodeSelector, 0);
    ASSERT(SUCCEEDED(status));

    // 07 - #NM - Device Not Available Exception
    status = CREATE_INTERRUPT_GATE_DESC(DeviceNotAvailable, ExceptionDeviceNotAvailable, CodeSelector, 0);
    ASSERT(SUCCEEDED(status));

    // 08 - #DF - Double Fault
    status = CREATE_INTERRUPT_GATE_DESC(DoubleFault, ExceptionDoubleFault, CodeSelector, IST_CHOOSE(IST_DF, NumberOfTssStacks));
    ASSERT(SUCCEEDED(status));

    // 09 - COS - Coprocessor Segment Overrrun
    status = CREATE_INTERRUPT_GATE_DESC(CoprocessorSegmentOverrun, ExceptionCoprocOverrun, CodeSelector, 0);
    ASSERT(SUCCEEDED(status));

    // 10 - #TS - Invalid TSS Exception
    status = CREATE_INTERRUPT_GATE_DESC(InvalidTSS, ExceptionInvalidTSS, CodeSelector, 0);
    ASSERT(SUCCEEDED(status));

    // 11 - #NP - Segment Not Present
    status = CREATE_INTERRUPT_GATE_DESC(SegmentNotPresent, ExceptionSegmentNotPresent, CodeSelector, IST_CHOOSE(IST_NP, NumberOfTssStacks));
    ASSERT(SUCCEEDED(status));

    // 12 - #SS - Stack Fault Exception
    status = CREATE_INTERRUPT_GATE_DESC(StackFault, ExceptionStackFault, CodeSelector, IST_CHOOSE(IST_SS, NumberOfTssStacks));
    ASSERT(SUCCEEDED(status));

    // 13 - #GP - General Protection
    status = CREATE_INTERRUPT_GATE_DESC(GeneralProtection, ExceptionGeneralProtection, CodeSelector, IST_CHOOSE(IST_GP, NumberOfTssStacks));
    ASSERT(SUCCEEDED(status));

    // 14 - #PF - Page Fault
    status = CREATE_INTERRUPT_GATE_DESC(PageFault, ExceptionPageFault, CodeSelector, 0);
    ASSERT(SUCCEEDED(status));

    // 16 - #MF - x87 FPU Floating-Point Error
    status = CREATE_INTERRUPT_GATE_DESC(FloatingPointX87Error, ExceptionX87FpuException, CodeSelector, 0);
    ASSERT(SUCCEEDED(status));

    // 17 - #AC - Alignment Check Exception
    status = CREATE_INTERRUPT_GATE_DESC(AlignmentCheck, ExceptionAlignmentCheck, CodeSelector, 0);
    ASSERT(SUCCEEDED(status));

    // 18 - #MC - Machine Check Exception
    status = CREATE_INTERRUPT_GATE_DESC(MachineCheck, ExceptionMachineCheck, CodeSelector, IST_CHOOSE(IST_MC, NumberOfTssStacks));
    ASSERT(SUCCEEDED(status));

    // 19 - #XM - SIMD Floating-Point Exception
    status = CREATE_INTERRUPT_GATE_DESC(FloatingPointSIMD, ExceptionSIMDFpuException, CodeSelector, 0);
    ASSERT(SUCCEEDED(status));

    // 20 - #VE - Virtualization Exception
    status = CREATE_INTERRUPT_GATE_DESC(VirtualizationException, ExceptionVirtualizationException, CodeSelector, 0);
    ASSERT(SUCCEEDED(status));

#pragma warning(pop)

    return status;
}

static
STATUS
_InitExternalInterruptHandlers(
    IN      WORD                CodeSelector
    )
{
    STATUS status;

    status = STATUS_SUCCESS;

#pragma warning(push)
    // warning C4152: nonstandard extension, function/data pointer conversion in expression
#pragma warning(disable:4152)
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(32); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(33); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(34); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(35);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(36); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(37); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(38); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(39);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(40); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(41); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(42); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(43);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(44); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(45); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(46); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(47);

    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(48); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(49); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(50); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(51);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(52); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(53); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(54); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(55);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(56); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(57); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(58); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(59);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(60); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(61); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(62); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(63);

    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(64); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(65); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(66); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(67);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(68); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(69); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(70); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(71);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(72); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(73); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(74); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(75);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(76); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(77); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(78); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(79);

    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(80); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(81); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(82); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(83);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(84); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(85); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(86); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(87);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(88); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(89); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(90); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(91);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(92); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(93); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(94); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(95);

    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(96); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(97); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(98); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(99);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(100); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(101); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(102); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(103);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(104); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(105); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(106); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(107);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(108); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(109); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(110); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(111);

    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(112); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(113); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(114); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(115);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(116); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(117); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(118); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(119);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(120); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(121); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(122); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(123);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(124); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(125); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(126); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(127);

    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(128); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(129); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(130); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(131);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(132); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(133); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(134); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(135);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(136); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(137); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(138); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(139);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(140); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(141); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(142); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(143);

    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(144); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(145); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(146); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(147);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(148); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(149); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(150); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(151);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(152); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(153); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(154); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(155);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(156); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(157); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(158); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(159);

    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(160); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(161); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(162); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(163);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(164); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(165); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(166); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(167);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(168); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(169); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(170); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(171);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(172); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(173); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(174); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(175);

    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(176); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(177); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(178); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(179);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(180); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(181); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(182); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(183);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(184); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(185); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(186); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(187);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(188); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(189); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(190); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(191);

    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(192); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(193); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(194); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(195);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(196); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(197); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(198); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(199);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(200); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(201); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(202); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(203);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(204); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(205); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(206); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(207);

    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(208); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(209); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(210); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(211);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(212); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(213); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(214); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(215);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(216); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(217); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(218); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(219);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(220); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(221); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(222); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(223);

    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(224); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(225); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(226); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(227);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(228); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(229); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(230); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(231);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(232); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(233); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(234); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(235);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(236); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(237); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(238); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(239);

    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(240); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(241); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(242); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(243);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(244); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(245); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(246); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(247);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(248); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(249); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(250); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(251);
    CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(252); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(253); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(254); CREATE_EXT_INTERRUPT_GATE_AND_CHECK_FAILURE(255);
#pragma warning(pop)

    return status;
}